### ISSUE TITLE
Server kicks everyone when using /lg joinAll

### ISSUE THREAD

**Issue by nohehf** [leomelki/LoupGarou#55]
I have the plugin running on a 1.15.2 spigot server, it worked well since today and i didn't changed anything. I first wondered that it was because of my server version (1.15.2) were the plugin is made for 1.15.1 so I downgraded and it still kicks people out, I've also tried to update the plugin from 1.0.1 to 1.1.0 but the problem is still happening. It also seems to happend randomly when people just connect to the server. Also it didn't stop spigot, and the /lg joinAll seems to work when i'm alone on the server and sometimes when we are only two. I've attached the part of the log. 
[error.log](https://github.com/leomelki/LoupGarou/files/4596090/error.log)

**Comment by Rigner** [comment]
Hey, can you provide a screenshot of the kick message clientside ? This will help to find out the issue 😄

**Comment by nohehf** [comment]
I use BungeeCord on my server so the error is:
![image](https://user-images.githubusercontent.com/64989428/81508194-0e296400-9303-11ea-9aad-825954aad3d9.png)
But the strange part is that i can go back on the server, it didn't stops.
(je peux parler français aussi si ça aide)

**Comment by leomelki** [comment]
Yes, you shouldn't use the plug-in with bungeecord for now since some bungeecord version are not happy with how I deal with teams :/

**Comment by nohehf** [comment]
The thing is that It worked well with it a week ago, I've not updated either of the plugin or bungee :/

**Comment by Vall98** [comment]
Hey, same issue here, I get kicked when trying to use "/lg joinAll". I'm using BungeeCord build 1523 and got this error (BungeeCord side):

> [SEVERE] [Vall98] <-> DownstreamBridge <-> [WereWolf] - encountered exception
> java.lang.IllegalArgumentException: Team PLAYER2 already exists in this scoreboard

On spigot-side, I only get an exception due to the fact the game doesn't find the players anymore (java.lang.NullPointerException: null at LGPlayer.java:258)

It seems that checking if the teams already exist before creating them could solve the issue.
Something like `myTeam.setMode(teamExist(p.getName()) ? 2 : 0);` (JoinListener.java:33) and `team.setMode(teamExist(player.getName()) ? 2 : 0);` (JoinListener.java:43) to update the teams if they already exist, unless it's better to remove the teams before creating them again.

I'm not familiar with the scoreboard system at all so I don't know how you can create the "teamExist" function.

If you can just say if I'm completely wrong or what's better between updating/removing the existing teams, I could try to understand the scoreboard system and then try to submit a pull request to solve this issue.

Hope it can help in anyway!


(Et je peux parler français aussi si ça aide)

**Comment by Rigner** [comment]
There are a few problems in the plugin, especially with how packets are handled.

This plugin is old and unsupported anymore, because it got moved to MC 1.9 (no idea why, this is sad because 1.15+ have a lot of a new cool features).

Also, I think @leomelki should mark this repo as archived, since it will no longer receive updates.

**Comment by leomelki** [comment]
@PSNRigner I moved the plug-in to 1.9 because when I was using 1.15, some players were getting kicked for no reason (and that's not great for Squeezie's livestream). 

This problem come from how I managed Scoreboard teams and it makes the plug-in not compatible with bungeecord because bungee checks if teams you create already exists or not.

**Comment by Rigner** [comment]
Yeah I noticed, some invalid packets were sent. I guess this is either a threading issue with like 2 packets overlapping, or ProtocolLib doing something wrong. Nothing related to the version. (I've been developing on 1.15+ since they are out, using NMS packets directly, and never had any issue)

**Comment by leomelki** [comment]
I forgot to reply here but, basically, it is because I send packets about creating a team even if the team already exist because the client don't care about that but Bungeecord does and throw an error ... @PSNRigner

**Comment by Rigner** [comment]
I've seen other errors related to packet deserialization, but yeah thanks for clarifying :)
